version: "3.8"
services:
  mongo-db:
    image: mongo:5.0
    container_name: mongoDB
    ports:
      - 27017:27017
    volumes: 
      - mymongodata:/data/db
      - type: bind
        source: ./mongo-entrypoint
        target: /docker-entrypoint-initdb.d/

volumes:
  mymongodata:
